<?php

require_once "data/Almacen.php";
require_once "data/DB.php";

class RN_Almacen extends DataBase {

    function __construct()
    {
        parent::Open();
    }

    /**
     * Obtiene la lista de almacenes que no han sido eliminados lógicamente
     */
    function GetList(){
        $sql = "SELECT * FROM almacenes WHERE estado = 1 AND deleted_at IS NULL";
        $res = $this->Execute($sql);
        
        $list = array();

        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);

            foreach ($data as $item) {
                $list[] = new Almacen(
                    $item["idAlmacen"],
                    $item["hashAlmacen"],
                    $item["nombre"],
                    $item["ubicacion"],
                    $item["tipo_almacen"],
                    $item["subtipo_almacen"],
                    $item["genera_alerta"],
                    $item["estado"]
                );
            }
        }

        return $list;
    }

    /**
     * Busca un almacén específico por su hash [cite: 24]
     */
    function GetData($_hashAlmacen){
        $sql = "SELECT * FROM almacenes WHERE hashAlmacen = '" . $_hashAlmacen . "'";
        $res = $this->Execute($sql);
        
        $oAlmacen = null;

        if ($this->ContainsData($res)){
            $row = $this->FetchArray($res);

            $oAlmacen = new Almacen(
                $row["idAlmacen"],
                $row["hashAlmacen"],
                $row["nombre"],
                $row["ubicacion"],
                $row["tipo_almacen"],
                $row["subtipo_almacen"],
                $row["genera_alerta"],
                $row["estado"]
            );
        }

        return $oAlmacen;
    }

    /**
     * Registra un nuevo almacén y genera su hash único
     */
    function Save($oAlmacen){
        $sql = "INSERT INTO almacenes (
            hashAlmacen,
            nombre,
            ubicacion,
            tipo_almacen,
            subtipo_almacen,
            genera_alerta,
            estado
        ) VALUES (
            'temp',
            '" . $oAlmacen->nombre . "',
            '" . $oAlmacen->ubicacion . "',
            '" . $oAlmacen->tipo_almacen . "',
            '" . $oAlmacen->subtipo_almacen . "',
            " . (int)$oAlmacen->genera_alerta . ",
            1
        )";

        $res = $this->Execute($sql);
        $id = $this->GetLastIdAutoGenerated();

        $sql2 = "UPDATE almacenes SET hashAlmacen = '" . sha1($id) . "' WHERE idAlmacen = " . $id;

        $this->Execute($sql2);
        return $res;
    }

    /**
     * Actualiza los datos de un almacén usando su hash
     */
    function Update($oAlmacen){
        $sql = "UPDATE almacenes SET 
            nombre = '" . $oAlmacen->nombre . "',
            ubicacion = '" . $oAlmacen->ubicacion . "',
            tipo_almacen = '" . $oAlmacen->tipo_almacen . "',
            subtipo_almacen = '" . $oAlmacen->subtipo_almacen . "',
            genera_alerta = " . (int)$oAlmacen->genera_alerta . "
            WHERE hashAlmacen = '" . $oAlmacen->hashAlmacen . "'";
        
        $res = $this->Execute($sql);
        return $res;
    }

    function Delete($_hashAlmacen){
        $sql = "UPDATE almacenes SET 
                estado = 0, 
                deleted_at = NOW() 
                WHERE hashAlmacen = '" . $_hashAlmacen . "'";
        
        $res = $this->Execute($sql);
        return $res;
    }
}
?>