<?php

require_once "data/Compra.php";
require_once "data/DB.php";

class RN_Compra extends DataBase {

    function __construct()
    {
        parent::Open();
    }

    /**
     * Obtiene la lista de compras con nombres de productos para la vista
     */
    function GetList(){
        $sql = "SELECT c.*, p.nombre as nomProducto, a.nombre as nomAlmacen 
                FROM compras c
                INNER JOIN productos p ON c.idProducto = p.idProducto
                INNER JOIN almacenes a ON c.idAlmacen = a.idAlmacen
                WHERE c.deleted_at IS NULL 
                ORDER BY c.fecha_compra DESC";
        
        $res = $this->Execute($sql);
        $list = array();

        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);
            foreach ($data as $item) {         
                $list[] = new Compra(
                    $item["idCompra"],
                    $item["hashCompra"],
                    $item["idProducto"],
                    $item["idAlmacen"],
                    $item["lote"],
                    $item["cantidad"],
                    $item["precio_unitario_compra"],
                    $item["fecha_compra"],
                    $item["deleted_at"]
                );
            }
        }
        return $list;
    }

    /**
     * Registra la compra e impacta el inventario (Doble acción)
     */
    function Save($oCompra){
        // 1. Insertamos la compra
        $sql = "INSERT INTO compras (hashCompra, idProducto, idAlmacen, lote, cantidad, precio_unitario_compra, fecha_compra) 
                VALUES (
                'temp',
                " . $oCompra->idProducto . ",
                " . $oCompra->idAlmacen . ",
                '" . $oCompra->lote . "',
                " . $oCompra->cantidad . ",
                " . $oCompra->precioUnitario . ",
                NOW())";

        $res = $this->Execute($sql);
        $id = $this->GetLastIdAutoGenerated();

        // 2. Generamos el hash único
        $hash = sha1($id);
        $sql2 = "UPDATE compras SET hashCompra = '" . $hash . "' WHERE idCompra = " . $id;
        $this->Execute($sql2);

        // 3. ¡IMPORTANTE! Disparamos el movimiento de inventario para la trazabilidad
        // Usamos la lógica de RN_Inventario que creamos antes
        require_once "RN_Inventario.php";
        $oRN_Inventario = new RN_Inventario();
        
        $motivo = "Compra Lote: " . $oCompra->lote;
        $oRN_Inventario->RegistrarMovimiento(
            $oCompra->idProducto, 
            $oCompra->idAlmacen, 
            'Entrada', 
            $oCompra->cantidad, 
            $motivo
        );

        return $id;
    }

    function Delete($_hashCompra){
        // Aplicamos Soft Delete como pide el documento [cite: 25, 26]
        $sql = "UPDATE compras SET deletedAt = NOW() WHERE hashCompra = '" . $_hashCompra . "'";
        return $this->Execute($sql);
    }
}