<?php

require_once "data/Produccion.php";
require_once "data/ProduccionDetalle.php";
require_once "data/DB.php";

class RN_Produccion extends DataBase
{
    function __construct()
    {
        parent::Open();
    }

    /**
     * Calcula cuantas unidades se pueden fabricar segun el stock actual
     * y el costo estimado basado en la ultima compra de cada insumo.
     */
    function ConsultarViabilidad($idReceta, $idAlmacen = 1)
    {
        $idReceta = (int)$idReceta;
        $idAlmacen = (int)$idAlmacen;

        $sql = "SELECT rd.idProducto, rd.cantidad_necesaria, i.stock_actual, p.nombre,
                (
                    SELECT cd.precio_unitario_base
                    FROM compra_detalle cd
                    INNER JOIN compras c ON c.idCompra = cd.idCompra
                    WHERE cd.idProducto = rd.idProducto
                      AND cd.deleted_at IS NULL
                      AND c.deleted_at IS NULL
                    ORDER BY c.fecha_compra DESC, cd.idCompraDetalle DESC
                    LIMIT 1
                ) AS ultimoPrecio
                FROM receta_detalles rd
                INNER JOIN inventarios i ON rd.idProducto = i.idProducto
                INNER JOIN productos p ON rd.idProducto = p.idProducto
                WHERE rd.idReceta = ?
                  AND i.idAlmacen = ?";

        $data = $this->fetchAll($sql, "ii", [$idReceta, $idAlmacen]);

        if (empty($data)) {
            return ["maxima" => 0, "costo_u" => 0, "insumos" => []];
        }

        $maximaProduccion = -1;
        $costoUnitarioInsumos = 0;
        $detalles = [];

        foreach ($data as $item) {
            $necesario = (float)$item['cantidad_necesaria'];
            $stock = (float)$item['stock_actual'];
            $precio = isset($item['ultimoPrecio']) ? (float)$item['ultimoPrecio'] : 0;

            if ($necesario > 0) {
                $posible = (int)floor($stock / $necesario);

                if ($maximaProduccion === -1 || $posible < $maximaProduccion) {
                    $maximaProduccion = $posible;
                }
            } else {
                $posible = 999999;
            }

            $costoUnitarioInsumos += ($necesario * $precio);

            $detalles[] = [
                "idProducto" => (int)$item['idProducto'],
                "nombre" => $item['nombre'],
                "necesario" => $necesario,
                "stock" => $stock,
                "precio_momento" => $precio,
                "alcance" => $posible,
            ];
        }

        return [
            "maxima" => ($maximaProduccion <= 0) ? 0 : $maximaProduccion,
            "costo_u" => $costoUnitarioInsumos,
            "insumos" => $detalles,
        ];
    }

    /**
     * Registra la produccion completa:
     * 1. Cabecera
     * 2. Detalle de consumo
     * 3. Salida de insumos
     * 4. Entrada de producto terminado
     */
    function RegistrarProduccion($idReceta, $cantidad, $idUsuario, $idAlmacenInsumos, $idAlmacenDestino)
    {
        $idReceta = (int)$idReceta;
        $cantidad = (int)$cantidad;
        $idUsuario = (int)$idUsuario;
        $idAlmacenInsumos = (int)$idAlmacenInsumos;
        $idAlmacenDestino = (int)$idAlmacenDestino;

        if ($idReceta <= 0 || $cantidad <= 0 || $idUsuario <= 0 || $idAlmacenInsumos <= 0 || $idAlmacenDestino <= 0) {
            throw new InvalidArgumentException("Datos de produccion invalidos.");
        }

        $viabilidad = $this->ConsultarViabilidad($idReceta, $idAlmacenInsumos);
        if ($cantidad > $viabilidad['maxima']) {
            return false;
        }

        $receta = $this->fetchOne(
            "SELECT idProductoFinal FROM recetas WHERE idReceta = ? LIMIT 1",
            "i",
            [$idReceta]
        );

        if (!$receta || empty($receta['idProductoFinal'])) {
            throw new RuntimeException("La receta no tiene producto final asociado.");
        }

        $idProdFinal = (int)$receta['idProductoFinal'];
        $costoLote = $viabilidad['costo_u'] * $cantidad;
        $hash = sha1(uniqid((string)$idReceta, true));
        $estado = 'Finalizado';

        try {
            $this->BeginTransaction();

            $insertCabecera = $this->executeStatement(
                "INSERT INTO producciones (hashProduccion, idReceta, cantidad_producida, costo_total_lote, idUsuario, estado)
                 VALUES (?, ?, ?, ?, ?, ?)",
                "siddis",
                [$hash, $idReceta, $cantidad, $costoLote, $idUsuario, $estado]
            );

            if (!$insertCabecera) {
                throw new RuntimeException("Error al insertar la cabecera de produccion.");
            }

            $idProduccion = (int)$this->GetLastIdAutoGenerated();
            if ($idProduccion <= 0) {
                throw new RuntimeException("No se pudo obtener el ID de produccion generado.");
            }

            foreach ($viabilidad['insumos'] as $ins) {
                $idProducto = (int)$ins['idProducto'];
                $cantidadUsada = (float)$ins['necesario'] * $cantidad;
                $precioMomento = (float)$ins['precio_momento'];

                if ($cantidadUsada <= 0) {
                    continue;
                }

                $detalleOk = $this->executeStatement(
                    "INSERT INTO produccion_detalle (idProduccion, idProducto, cantidad_usada, precio_unitario_momento)
                     VALUES (?, ?, ?, ?)",
                    "iidd",
                    [$idProduccion, $idProducto, $cantidadUsada, $precioMomento]
                );

                if (!$detalleOk) {
                    throw new RuntimeException("Error al registrar el detalle de produccion.");
                }

                $stockOk = $this->executeStatement(
                    "UPDATE inventarios
                     SET stock_actual = stock_actual - ?
                     WHERE idProducto = ? AND idAlmacen = ?",
                    "dii",
                    [$cantidadUsada, $idProducto, $idAlmacenInsumos]
                );

                if (!$stockOk) {
                    throw new RuntimeException("Error al descontar stock de insumos.");
                }

                $movSalidaOk = $this->executeStatement(
                    "INSERT INTO movimientos (idProducto, idAlmacen, tipo, cantidad, motivo)
                     VALUES (?, ?, 'Salida', ?, ?)",
                    "iids",
                    [$idProducto, $idAlmacenInsumos, $cantidadUsada, "Consumo Produccion #{$idProduccion}"]
                );

                if (!$movSalidaOk) {
                    throw new RuntimeException("Error al registrar movimiento de salida.");
                }
            }

            $inventarioFinal = $this->fetchOne(
                "SELECT idProducto
                 FROM inventarios
                 WHERE idProducto = ? AND idAlmacen = ?
                 LIMIT 1",
                "ii",
                [$idProdFinal, $idAlmacenDestino]
            );

            if ($inventarioFinal) {
                $stockFinalOk = $this->executeStatement(
                    "UPDATE inventarios
                     SET stock_actual = stock_actual + ?
                     WHERE idProducto = ? AND idAlmacen = ?",
                    "dii",
                    [$cantidad, $idProdFinal, $idAlmacenDestino]
                );
            } else {
                $stockFinalOk = $this->executeStatement(
                    "INSERT INTO inventarios (idProducto, idAlmacen, stock_actual, punto_critico)
                     VALUES (?, ?, ?, 0)",
                    "iid",
                    [$idProdFinal, $idAlmacenDestino, $cantidad]
                );
            }

            if (!$stockFinalOk) {
                throw new RuntimeException("Error al registrar inventario de producto terminado.");
            }

            $movEntradaOk = $this->executeStatement(
                "INSERT INTO movimientos (idProducto, idAlmacen, tipo, cantidad, motivo)
                 VALUES (?, ?, 'Entrada', ?, ?)",
                "iids",
                [$idProdFinal, $idAlmacenDestino, $cantidad, "Ingreso Produccion #{$idProduccion}"]
            );

            if (!$movEntradaOk) {
                throw new RuntimeException("Error al registrar movimiento de entrada.");
            }

            $this->Commit();
            return $hash;
        } catch (Throwable $e) {
            $this->Rollback();
            throw $e;
        }
    }

    function GetList()
    {
        $sql = "SELECT p.*, r.nombre_servicio AS nomReceta, u.nombre AS nomUsuario, prod.nombre AS nomProductoFinal
                FROM producciones p
                LEFT JOIN recetas r ON p.idReceta = r.idReceta
                LEFT JOIN usuario u ON p.idUsuario = u.idUsuario
                LEFT JOIN productos prod ON r.idProductoFinal = prod.idProducto
                ORDER BY p.idProduccion DESC";

        $res = $this->Execute($sql);
        $list = array();

        if ($this->ContainsData($res)) {
            $data = $this->DataListStructure($res);

            foreach ($data as $item) {
                $objP = new Produccion(
                    $item["idProduccion"],
                    $item["hashProduccion"],
                    $item["idReceta"],
                    $item["cantidad_producida"],
                    $item["costo_total_lote"],
                    $item["fecha_produccion"],
                    $item["idUsuario"],
                    $item["estado"] ?? 'Finalizado'
                );

                $objP->nomReceta = $item["nomReceta"];
                $objP->nomUsuario = $item["nomUsuario"];
                $objP->nomProductoFinal = $item["nomProductoFinal"];

                $list[] = $objP;
            }
        }

        return $list;
    }
}

?>
