<?php

require_once "data/Producto.php";
require_once "data/DB.php";

class RN_Producto extends DataBase {

    function __construct()
    {
        parent::Open();
    }

    /**
     * Obtiene la lista de insumos/productos activos
     */
    function GetList(){
        // Filtramos por estado 1 y que no haya sido borrado (Soft Delete)
        $sql = "SELECT * FROM productos WHERE estado = 1 AND deleted_at IS NULL";
        $res = $this->Execute($sql);
        
        $list = array();

        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);

            foreach ($data as $item) {
                $list[] = new Producto(
                    $item["idProducto"],
                    $item["hashProducto"],
                    $item["nombre"],
                    $item["sku"],
                    $item["unidad_medida"],
                    $item["tipo"],
                    $item["estado"]
                );
            }
        }

        return $list;
    }

    /**
     * Obtiene la lista de insumos activos
     */
    function GetListInsumo(){
        // Filtramos por estado 1 y que no haya sido borrado (Soft Delete)
        $sql = "SELECT * FROM productos WHERE estado = 1 AND deleted_at IS NULL AND tipo = 'Insumo'";
        $res = $this->Execute($sql);
        
        $list = array();

        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);

            foreach ($data as $item) {
                $list[] = new Producto(
                    $item["idProducto"],
                    $item["hashProducto"],
                    $item["nombre"],
                    $item["sku"],
                    $item["unidad_medida"],
                    $item["tipo"],
                    $item["estado"]
                );
            }
        }

        return $list;
    }

    /**
     * Obtiene un producto específico mediante su hash
     */
    function GetData($_hashProducto){
        $sql = "SELECT * FROM productos WHERE hashProducto = '" . $_hashProducto . "'";
        $res = $this->Execute($sql);
        
        $oProducto = null;

        if ($this->ContainsData($res)){
            $row = $this->FetchArray($res);

            $oProducto = new Producto(
                    $row["idProducto"],
                    $row["hashProducto"],
                    $row["nombre"],
                    $row["sku"],
                    $row["unidad_medida"],
                    $row["tipo"],
                    $row["estado"]
                );
        }

        return $oProducto;
    }

    /**
     * Registra un nuevo producto e insumo
     */
    function Save($oProducto){
        // Usamos NULL para el idProducto (autoincremental) y 'temp' para el hash inicial
        $sql = "INSERT INTO productos (hashProducto, nombre, sku, unidad_medida, tipo, estado) 
                VALUES (
                'temp',
                '" . $oProducto->nombre . "',
                '" . $oProducto->sku . "',
                '" . $oProducto->unidad_medida . "',
                '" . $oProducto->tipo . "',
                1)";
    
        $res = $this->Execute($sql);
        $id = $this->GetLastIdAutoGenerated();

        // Generación del hash tras la inserción para asegurar unicidad
        $sql2 = "UPDATE productos SET hashProducto = '" . sha1($id) . "' WHERE idProducto = " . $id;

        $this->Execute($sql2);
        return $res;
    }

    /**
     * Actualiza la información del producto
     */
    function Update($oProducto){
        $sql = "UPDATE productos SET 
                nombre = '" . $oProducto->nombre . "',
                sku = '" . $oProducto->sku . "',
                unidad_medida = '" . $oProducto->unidad_medida . "',
                tipo = '" . $oProducto->tipo . "'
                WHERE hashProducto = '" . $oProducto->hashProducto . "'";
        
        $res = $this->Execute($sql);
        return $res;
    }

    /**
     * Borrado lógico (Soft Delete)
     */
    function Delete($_hashProducto){
        // Cambiamos estado a 0 y registramos la fecha de eliminación
        $sql = "UPDATE productos SET 
                estado = 0, 
                deleted_at = NOW() 
                WHERE hashProducto = '" . $_hashProducto . "'";
        
        $res = $this->Execute($sql);
        return $res;
    }
}

?>