<?php

require_once "data/Receta.php";
require_once "data/RecetaDetalle.php";
require_once "data/DB.php";

class RN_Receta extends DataBase {

    function __construct()
    {
        parent::Open();
    }

    /**
     * Lista todas las recetas activas incluyendo el producto final asociado
     */
    function GetList(){
        // Hacemos un JOIN para traer el nombre del producto final y mostrarlo en la lista
        $sql = "SELECT r.*, p.nombre as nomProductoFinal 
                FROM recetas r
                INNER JOIN productos p ON r.idProductoFinal = p.idProducto
                WHERE r.deleted_at IS NULL 
                ORDER BY r.nombre_servicio ASC";
        
        $res = $this->Execute($sql);
        $list = array();

        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);
            foreach ($data as $item) {         
                $oReceta = new Receta(
                    $item["idReceta"],
                    $item["hashReceta"],
                    $item["nombre_servicio"],
                    $item["costo_operativo_sugerido"],
                    $item["estado"],
                    $item["deleted_at"],
                    $item["idProductoFinal"]
                );
                // Propiedad virtual para mostrar en la lista del Kardex o Catálogo
                $oReceta->nomProductoFinal = $item["nomProductoFinal"];
                $list[] = $oReceta;
            }
        }
        return $list;
    }

    /**
     * Obtiene una receta completa con sus detalles y el ID del producto que genera
     */
    function GetData($_hashReceta){
        $sql = "SELECT * FROM recetas WHERE hashReceta = '" . $_hashReceta . "'";
        $res = $this->Execute($sql);
        
        if (!$this->ContainsData($res)) return null;
        $row = $this->FetchArray($res);

        $oReceta = new Receta(
            $row["idReceta"],
            $row["hashReceta"],
            $row["nombre_servicio"],
            $row["costo_operativo_sugerido"],
            $row["estado"],
            $row["deleted_at"],
            $row["idProductoFinal"]
        );

        $oReceta->detalles = $this->GetDetalles($oReceta->idReceta);

        return $oReceta;
    }

    private function GetDetalles($_idReceta){
        $sql = "SELECT rd.*, p.nombre as nomInsumo, p.unidad_medida 
                FROM receta_detalles rd
                INNER JOIN productos p ON rd.idProducto = p.idProducto
                WHERE rd.idReceta = " . $_idReceta;
        
        $res = $this->Execute($sql);
        $list = array();

        if ($this->ContainsData($res)){
            $data = $this->DataListStructure($res);
            foreach ($data as $item) {
                $oDet = new RecetaDetalle(
                    $item["idDetalle"],
                    $item["idReceta"],
                    $item["idProducto"],
                    $item["cantidadNecesaria"]
                );
                $oDet->nomInsumo = $item["nomInsumo"];
                $oDet->uMedida = $item["unidad_medida"];
                $list[] = $oDet;
            }
        }
        return $list;
    }

    /**
     * Guarda la receta vinculándola al producto final que se "venderá"
     */
    function Save($oReceta, $listaDetalles){
        // 1. Insertar Cabecera incluyendo idProductoFinal
        $sql = "INSERT INTO recetas (nombre_servicio, costo_operativo_sugerido, estado, idProductoFinal) 
                VALUES (
                    '".$oReceta->nombre_servicio."', 
                    ".$oReceta->costo_operativo_sugerido.", 
                    'Activo', 
                    ".$oReceta->idProductoFinal."
                )";
        
        $this->Execute($sql);
        $id = $this->GetLastIdAutoGenerated();
        
        // 2. Generar Hash único para la receta
        $hash = sha1($id);
        $this->Execute("UPDATE recetas SET hashReceta = '$hash' WHERE idReceta = $id");

        // 3. Insertar Detalles (Insumos/Materia Prima)
        foreach($listaDetalles as $oDet){
            $sqlDet = "INSERT INTO receta_detalles (idReceta, idProducto, cantidad_necesaria) 
                       VALUES ($id, ".$oDet->idProducto.", ".$oDet->cantidadNecesaria.")";
            $this->Execute($sqlDet);
        }

        return $hash;
    }

    /**
     * Calcula el costo sumando el precio de la última compra de cada ingrediente
     */
    function CalcularCostoProduccion($_idReceta){
        $sql = "SELECT SUM(rd.cantidad_necesaria * (
                    SELECT c.precio_unitario_compra FROM compras c 
                    WHERE c.idProducto = rd.idProducto 
                    ORDER BY c.fecha_compra DESC LIMIT 1
                )) as costoTotal
                FROM receta_detalles rd
                WHERE rd.idReceta = " . $_idReceta;

        $res = $this->Execute($sql);
        if ($this->ContainsData($res)){
            $row = $this->FetchArray($res);
            return $row["costoTotal"] ?? 0;
        }
        return 0;
    }

    function Delete($_hashReceta){
        $sql = "UPDATE recetas SET deleted_at = NOW(), estado = 'Inactivo' WHERE hashReceta = '$_hashReceta'";
        return $this->Execute($sql);
    }
}