<?php

require_once "data/Usuario.php";
require_once "data/DB.php";

class RN_Usuario extends DataBase
{
    function __construct()
    {
        $this->Open();
    }

    function GetList()
    {
        $sql = "SELECT idUsuario, hashUsuario, nombre, username, pswd, idPerfil, estado
                FROM usuario";

        $rows = $this->fetchAll($sql);
        $list = array();

        foreach ($rows as $item) {
            $list[] = new Usuario(
                $item["idUsuario"],
                $item["hashUsuario"],
                $item["nombre"],
                $item["username"],
                $item["pswd"],
                $item["idPerfil"],
                $item["estado"]
            );
        }

        return $list;
    }

    function GetData($hashUsuario)
    {
        $sql = "SELECT idUsuario, hashUsuario, nombre, username, pswd, idPerfil, estado
                FROM usuario
                WHERE hashUsuario = ?
                LIMIT 1";

        $item = $this->fetchOne($sql, "s", [$hashUsuario]);

        if (!$item) {
            return null;
        }

        $plainPassword = "";

        if ($this->isPasswordHash($item["pswd"])) {
            $plainPassword = "";
        } else {
            $legacy = $this->fetchOne(
                "SELECT CAST(AES_DECRYPT(pswd, ?) AS CHAR(255)) AS pswd_legacy
                 FROM usuario
                 WHERE idUsuario = ?
                 LIMIT 1",
                "si",
                [UK, (int)$item["idUsuario"]]
            );

            $plainPassword = $legacy && isset($legacy["pswd_legacy"])
                ? $legacy["pswd_legacy"]
                : "";
        }

        return new Usuario(
            $item["idUsuario"],
            $item["hashUsuario"],
            $item["nombre"],
            $item["username"],
            $plainPassword,
            $item["idPerfil"],
            $item["estado"]
        );
    }

    function Save($oUsuario)
    {
        $hashedPassword = password_hash($oUsuario->pswd, PASSWORD_DEFAULT);

        // Omitimos idUsuario para que la BD use el AUTO_INCREMENT
        $sql = "INSERT INTO usuario 
                (hashUsuario, nombre, username, pswd, idPerfil, estado) 
                VALUES (?, ?, ?, ?, ?, ?)";

        $res = $this->executeStatement(
            $sql, 
            "ssssis", 
            [
                $oUsuario->hashUsuario, 
                $oUsuario->nombre, 
                $oUsuario->username, 
                $hashedPassword, 
                (int)$oUsuario->idPerfil, 
                $oUsuario->estado
            ]
        );

        if ($res) {
            $id = $this->GetLastIdAutoGenerated();
            
            if ($id > 0) {
                $newHash = sha1($id); // Genera el hash de 40 caracteres basado en el ID real
                
                $this->executeStatement(
                    "UPDATE usuario SET hashUsuario = ? WHERE idUsuario = ?",
                    "si",
                    [$newHash, (int)$id]
                );
            }
        }

        return $res;
    }

    function Update($oUsuario)
    {
        if (!empty($oUsuario->pswd)) {
            $hashedPassword = password_hash($oUsuario->pswd, PASSWORD_DEFAULT);

            return $this->executeStatement(
                "UPDATE usuario
                 SET nombre = ?, username = ?, pswd = ?, idPerfil = ?, estado = ?
                 WHERE hashUsuario = ?",
                "sssiss",
                [
                    $oUsuario->nombre,
                    $oUsuario->username,
                    $hashedPassword,
                    (int)$oUsuario->idPerfil,
                    $oUsuario->estado,
                    $oUsuario->hashUsuario
                ]
            );
        }

        return $this->executeStatement(
            "UPDATE usuario
             SET nombre = ?, username = ?, idPerfil = ?, estado = ?
             WHERE hashUsuario = ?",
            "ssiss",
            [
                $oUsuario->nombre,
                $oUsuario->username,
                (int)$oUsuario->idPerfil,
                $oUsuario->estado,
                $oUsuario->hashUsuario
            ]
        );
    }

    function Delete($hashUsuario)
    {
        return $this->executeStatement(
            "UPDATE usuario SET estado = ? WHERE hashUsuario = ?",
            "ss",
            ["Inactivo", $hashUsuario]
        );
    }

    function Verificar($_username, $_pswd)
    {
        $sql = "SELECT idUsuario, hashUsuario, username, pswd, idPerfil, estado
                FROM usuario
                WHERE username = ?
                LIMIT 1";

        $row = $this->fetchOne($sql, "s", [$_username]);

        if (!$row) {
            return false;
        }

        if (!isset($row["estado"]) || strtolower($row["estado"]) !== "activo") {
            return false;
        }

        $storedPassword = $row["pswd"];

        if ($this->isPasswordHash($storedPassword)) {
            if (password_verify($_pswd, $storedPassword)) {
                return $row["hashUsuario"];
            }

            return false;
        }

        $legacy = $this->fetchOne(
            "SELECT CAST(AES_DECRYPT(pswd, ?) AS CHAR(255)) AS pswd_legacy
             FROM usuario
             WHERE idUsuario = ?
             LIMIT 1",
            "si",
            [UK, (int)$row["idUsuario"]]
        );

        if (!$legacy || !isset($legacy["pswd_legacy"])) {
            return false;
        }

        if (!hash_equals((string)$legacy["pswd_legacy"], (string)$_pswd)) {
            return false;
        }

        $newHash = password_hash($_pswd, PASSWORD_DEFAULT);

        $this->executeStatement(
            "UPDATE usuario SET pswd = ? WHERE idUsuario = ?",
            "si",
            [$newHash, (int)$row["idUsuario"]]
        );

        return $row["hashUsuario"];
    }

    private function isPasswordHash($value)
    {
        if (!is_string($value) || $value === "") {
            return false;
        }

        return password_get_info($value)["algo"] !== null;
    }
}

?>