<?php

/**
 * @author      Francisco Bailaba
 * @company     Bylaba Projects
 * @copyright   2026
 * @version     1.1
 */

set_time_limit(0);

mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

require_once "Config.php";

class DataBase
{
    private $serverName = "localhost:3306"; // :3308
    private $user = "root";
    private $pswd = "";
    private $dbName = "creative_spot_db";

    private $link = null;
    private $op = 1; // 1: xamp, 2: easyphp

    public function Open()
    {
        if ($this->link instanceof mysqli) {
            return $this->link;
        }

        if ($this->op === 1) {
            $this->link = mysqli_connect(
                $this->serverName,
                $this->user,
                $this->pswd,
                $this->dbName
            );

            mysqli_set_charset($this->link, "utf8mb4");
        }

        return $this->link;
    }

    /**
     * Ejecuta una consulta preparada o simple.
     *
     * @param string $sql
     * @param string $types
     * @param array $params
     * @return mysqli_result|bool
     */
    public function query(string $sql, string $types = '', array $params = [])
    {
        $link = $this->Open();

        if (!empty($params)) {
            $stmt = mysqli_prepare($link, $sql);

            if ($stmt === false) {
                throw new Exception("No se pudo preparar la consulta.");
            }

            mysqli_stmt_bind_param($stmt, $types, ...$params);
            mysqli_stmt_execute($stmt);

            $result = mysqli_stmt_get_result($stmt);

            if ($result !== false) {
                return $result;
            }

            return true;
        }

        return mysqli_query($link, $sql);
    }

    /**
     * Devuelve una sola fila asociativa o null.
     *
     * @param string $sql
     * @param string $types
     * @param array $params
     * @return array|null
     */
    public function fetchOne(string $sql, string $types = '', array $params = []): ?array
    {
        $result = $this->query($sql, $types, $params);

        if ($result instanceof mysqli_result) {
            $row = mysqli_fetch_assoc($result);
            mysqli_free_result($result);
            return $row ?: null;
        }

        return null;
    }

    /**
     * Devuelve todas las filas como array asociativo.
     *
     * @param string $sql
     * @param string $types
     * @param array $params
     * @return array
     */
    public function fetchAll(string $sql, string $types = '', array $params = []): array
    {
        $result = $this->query($sql, $types, $params);

        if ($result instanceof mysqli_result) {
            $rows = mysqli_fetch_all($result, MYSQLI_ASSOC);
            mysqli_free_result($result);
            return $rows;
        }

        return [];
    }

    /**
     * Ejecuta INSERT, UPDATE, DELETE preparados o simples.
     *
     * @param string $sql
     * @param string $types
     * @param array $params
     * @return bool
     */
    public function executeStatement(string $sql, string $types = '', array $params = []): bool
    {
        $result = $this->query($sql, $types, $params);
        return $result === true || $result instanceof mysqli_result;
    }

    /**
     * Compatibilidad con el código viejo.
     *
     * @param string $_sql
     * @return mysqli_result|bool
     */
    public function Execute($_sql)
    {
        return $this->query($_sql);
    }

    public function GetLastIdAutoGenerated()
    {
        return mysqli_insert_id($this->Open());
    }

    public function ContainsData($res)
    {
        if ($res instanceof mysqli_result) {
            return mysqli_num_rows($res) > 0;
        }

        return false;
    }

    public function DataListStructure($_res)
    {
        $ret = [];

        if ($_res instanceof mysqli_result) {
            while ($row = mysqli_fetch_assoc($_res)) {
                $ret[] = $row;
            }
        }

        return $ret;
    }

    public function FetchArray($_res)
    {
        if ($_res instanceof mysqli_result) {
            return mysqli_fetch_array($_res);
        }

        return false;
    }

    public function BeginTransaction()
    {
        mysqli_begin_transaction($this->Open());
    }

    public function Commit()
    {
        mysqli_commit($this->Open());
    }

    public function Rollback()
    {
        mysqli_rollback($this->Open());
    }

    public function Close()
    {
        if ($this->link instanceof mysqli) {
            mysqli_close($this->link);
            $this->link = null;
        }
    }
}

?>